const Data =
    [
        {
            "names" : ["BZO-POXIZID", "Pentyl MDA-19", "5C-MDA-19"],
            "iupac_name": "N-[(Z)-(2-oxo-1-pentyl-indolin-3-ylidene)amino]benzamide",
            "classes" : ["Test"],
            "inchi" : "InChI=1S/C20H21N3O2/c1-2-3-9-14-23-17-13-8-7-12-16(17)18(20(23)25)21-22-19(24)15-10-5-4-6-11-15/h4-8,10-13H,2-3,9,14H2,1H3,(H,22,24)/b21-18-",
            "inchi_key": "Test",
            "smiles" : "Test",
            "cas_num": "1048973-64-3",
            "formula": "C20H21N3O2",
            "molecular_mass": "335.4",
            "molecular_ion_[m+]": "335",
            "exact_mass_[m+h]+": "336.1707",
            "source_name" : "cfsre",
            "source_url" : "https://www.cfsre.org/images/monographs/ortho-Methylfentanyl-New-Drug-Monograph-NPS-Discovery-122023.pdf",
        },
        {
            "names" : ["ortho-Methylfentanyl", "o-Methylfentany", "ortho-Methyl Fentanyl"],
            "iupac_name": "Test",
            "classes" : ["Test"],
            "inchi" : "Test",
            "inchi_key": "DPAJFOSXYXNYMA-UHFFFAOYSA-N",
            "smiles" : "Test",
            "cas_num": "1443-53-4",
            "formula": "C23H30N2O",
            "molecular_mass": "350.50",
            "molecular_ion_[m+]": "350",
            "exact_mass_[m+h]+": "351.2431",
            "source_name" : "cfsre",
            "source_url" : "https://www.cfsre.org/images/monographs/ortho-Methylfentanyl-New-Drug-Monograph-NPS-Discovery-122023.pdf",
        },
        {
            "names" : ["N-Desethyl Etonitazene"],
            "iupac_name": "Test",
            "classes" : ["Test"],
            "inchi" : "Test",
            "inchi_key": "RESPFUMJVJRUMB-UHFFFAOYSA-N",
            "smiles" : "Test",
            "cas_num": "2732926-26-8",
            "formula": "C20H24N4O3",
            "molecular_mass": "368.43",
            "molecular_ion_[m+]": "368",
            "exact_mass_[m+h]+": "369.1921",
            "source_name" : "cfsre",
            "source_url" : "https://www.cfsre.org/images/monographs/N-Desethyl-Etonitazene-New-Drug-Monograph-NPS-Discovery-113023.pdf",
        }
]